version: '3.8'

services:
  deep_ros_gpu:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        ROS_DISTRO: humble
        TARGETARCH: gpu
        CUDA_VERSION: 12.2.2
        UBUNTU_VERSION: 22.04
        TENSORRT_RUNTIME_VERSION: 10.9.0.34
        TENSORRT_CUDA_VERSION: 12.8
        USERNAME: developer
        USER_UID: 1000
        USER_GID: 1000
    image: deep_ros:gpu
    container_name: deep_ros_gpu_dev
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/deep_ros_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /deep_ros_ws
    network_mode: host
    stdin_open: true
    tty: true
    command: bash -c "source /opt/ros/humble/setup.bash && bash"

  deep_ros_cpu:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        ROS_DISTRO: humble
        TARGETARCH: cpu
        USERNAME: developer
        USER_UID: 1000
        USER_GID: 1000
    image: deep_ros:cpu
    container_name: deep_ros_cpu_dev
    volumes:
      - .:/deep_ros_ws
    working_dir: /deep_ros_ws
    network_mode: host
    stdin_open: true
    tty: true
    command: bash -c "source /opt/ros/humble/setup.bash && bash"

